In [4]:
# _*_ coding : utf-8 _*_
# @Time : 2023/11/8 21:56
# @Author : Liu kebing
# @File : construct_dataset_CG
# @Project : HGNN try1

import pandas as pd
import numpy as np
import scipy.io as sio

In [5]:
data_dir = r"C:\Users\liuke\chatgpt话题热度按周预测\代码\3-7月话题微博特征和总数.csv"
data = pd.read_csv(data_dir)
data

Unnamed: 0  微博数  微博总长度  微博包含艾特数  微博转发数  微博评论数  微博点赞数  微博总互动数  \
0     2022-2023影响世界华人盛典   15   3644        0     21     42    142     205   
1              2023上海车展    1    348        0    219     84    121     424   
2          2023世界人工智能大会    1    551        0     10     61     36     107   
3             2023中关村论坛    1    242        0      0      0      0       0   
4      2023中国国际大数据产业博览会    1    287        0      0      1      1       2   
...                 ...  ...    ...      ...    ...    ...    ...     ...   
1061                高血压    3   1821        0     12      1     16      29   
1062               鸟鸟分鸟    7   1400        0     32     30    133     195   
1063        鹿晗elle五月刊封面    8    697        3     37     39    321     397   
1064           鹿晗想演邓超父亲    8    950        0      0      1     39      40   
1065       黄磊吴越都没考上徐峥的班   18  19562        0      0      0      0       0   

        a     n     v    d  final_blogs_number  
0      30   331   405   95                  16  
1       3    43    32   15                   8  
2       2    58    37    4                  33  
3       1    32    16    5                   5  
4       1    46    20    3                   6  
...   ...   ...   ...  ...                 ...  
1061   55   225   191   46                   7  
1062   27   214   132   37                   9  
1063   14    47    65   22                   8  
1064    7    78   122   32                   8  
1065  127  1920  1620  400                  18  

[1066 rows x 13 columns]

In [6]:
fts = data.iloc[:,1:12]
fts = fts.to_numpy()
fts

array([[   15,  3644,     0, ...,   331,   405,    95],
       [    1,   348,     0, ...,    43,    32,    15],
       [    1,   551,     0, ...,    58,    37,     4],
       ...,
       [    8,   697,     3, ...,    47,    65,    22],
       [    8,   950,     0, ...,    78,   122,    32],
       [   18, 19562,     0, ...,  1920,  1620,   400]], dtype=int64)

In [7]:
times = data.iloc[:,12].to_list()
times

[16,
 8,
 33,
 5,
 6,
 5,
 18,
 8,
 14,
 15,
 12,
 10,
 18,
 9,
 9,
 5,
 7,
 8,
 9,
 23,
 8,
 18,
 6,
 56,
 17,
 6,
 6,
 51,
 13,
 7,
 5,
 6,
 20,
 8,
 11,
 11,
 16,
 5,
 38,
 9,
 6,
 47,
 6,
 5,
 12,
 24,
 7,
 16,
 10,
 6,
 9,
 10,
 9,
 8,
 7,
 10,
 5,
 40,
 6,
 11,
 11,
 5,
 25,
 5,
 7,
 25,
 13,
 16,
 17,
 55,
 54,
 104,
 16,
 13,
 7,
 25,
 42,
 10,
 21,
 7,
 3,
 17,
 7,
 6,
 24,
 10,
 7,
 57,
 98,
 6,
 7,
 18,
 5,
 16,
 18,
 8,
 11,
 18,
 10,
 15,
 9,
 5,
 8,
 14,
 5,
 6,
 54,
 18,
 5,
 7,
 6,
 7,
 5,
 26,
 22,
 16,
 5,
 38,
 5,
 7,
 26,
 8,
 6,
 8,
 33,
 11,
 5,
 5,
 16,
 31,
 26,
 12,
 53,
 68,
 6,
 7,
 628,
 18,
 6,
 6,
 18,
 6,
 504,
 5,
 9,
 10,
 11,
 5,
 10,
 22,
 6,
 86,
 44,
 48,
 32,
 19,
 190,
 27,
 4,
 13,
 5,
 12,
 8,
 11,
 13,
 13,
 13,
 53,
 12,
 11,
 8,
 10,
 8,
 27,
 13,
 22,
 5,
 8,
 9,
 6,
 5,
 7,
 49,
 19,
 17,
 22,
 5,
 6,
 6,
 29,
 102,
 5,
 11,
 5,
 5,
 17,
 6,
 7,
 18,
 7,
 8,
 5,
 100,
 92,
 56,
 29,
 36,
 90,
 6,
 19,
 7,
 71,
 18,
 17,
 17,
 6,
 6,
 56,
 7

In [8]:
lbls = np.zeros(1066)
count = 0
for i in times:
    if int(i)>=195:
        lbls[count] = 0
    elif int(i) >= 63:
        lbls[count] = 1
    elif int(i) >= 38:
        lbls[count] = 2
    else:
        lbls[count] = 3
    count = count + 1
    

In [9]:
indices = {}
for i in range(1066):
    if i < 853:
        indices[i] = 1
    else:
        indices[i] = 0

In [10]:
indices

{0: 1,
 1: 1,
 2: 1,
 3: 1,
 4: 1,
 5: 1,
 6: 1,
 7: 1,
 8: 1,
 9: 1,
 10: 1,
 11: 1,
 12: 1,
 13: 1,
 14: 1,
 15: 1,
 16: 1,
 17: 1,
 18: 1,
 19: 1,
 20: 1,
 21: 1,
 22: 1,
 23: 1,
 24: 1,
 25: 1,
 26: 1,
 27: 1,
 28: 1,
 29: 1,
 30: 1,
 31: 1,
 32: 1,
 33: 1,
 34: 1,
 35: 1,
 36: 1,
 37: 1,
 38: 1,
 39: 1,
 40: 1,
 41: 1,
 42: 1,
 43: 1,
 44: 1,
 45: 1,
 46: 1,
 47: 1,
 48: 1,
 49: 1,
 50: 1,
 51: 1,
 52: 1,
 53: 1,
 54: 1,
 55: 1,
 56: 1,
 57: 1,
 58: 1,
 59: 1,
 60: 1,
 61: 1,
 62: 1,
 63: 1,
 64: 1,
 65: 1,
 66: 1,
 67: 1,
 68: 1,
 69: 1,
 70: 1,
 71: 1,
 72: 1,
 73: 1,
 74: 1,
 75: 1,
 76: 1,
 77: 1,
 78: 1,
 79: 1,
 80: 1,
 81: 1,
 82: 1,
 83: 1,
 84: 1,
 85: 1,
 86: 1,
 87: 1,
 88: 1,
 89: 1,
 90: 1,
 91: 1,
 92: 1,
 93: 1,
 94: 1,
 95: 1,
 96: 1,
 97: 1,
 98: 1,
 99: 1,
 100: 1,
 101: 1,
 102: 1,
 103: 1,
 104: 1,
 105: 1,
 106: 1,
 107: 1,
 108: 1,
 109: 1,
 110: 1,
 111: 1,
 112: 1,
 113: 1,
 114: 1,
 115: 1,
 116: 1,
 117: 1,
 118: 1,
 119: 1,
 120: 1,
 121: 1,
 122: 1,
 12

In [14]:
data_dict = {}
data_dict['X'] = fts
data_dict['Y'] = times
data_dict['indices'] = indices

In [15]:
data_dict

{'X': array([[   15,  3644,     0, ...,   331,   405,    95],
        [    1,   348,     0, ...,    43,    32,    15],
        [    1,   551,     0, ...,    58,    37,     4],
        ...,
        [    8,   697,     3, ...,    47,    65,    22],
        [    8,   950,     0, ...,    78,   122,    32],
        [   18, 19562,     0, ...,  1920,  1620,   400]], dtype=int64),
 'Y': [16,
  8,
  33,
  5,
  6,
  5,
  18,
  8,
  14,
  15,
  12,
  10,
  18,
  9,
  9,
  5,
  7,
  8,
  9,
  23,
  8,
  18,
  6,
  56,
  17,
  6,
  6,
  51,
  13,
  7,
  5,
  6,
  20,
  8,
  11,
  11,
  16,
  5,
  38,
  9,
  6,
  47,
  6,
  5,
  12,
  24,
  7,
  16,
  10,
  6,
  9,
  10,
  9,
  8,
  7,
  10,
  5,
  40,
  6,
  11,
  11,
  5,
  25,
  5,
  7,
  25,
  13,
  16,
  17,
  55,
  54,
  104,
  16,
  13,
  7,
  25,
  42,
  10,
  21,
  7,
  3,
  17,
  7,
  6,
  24,
  10,
  7,
  57,
  98,
  6,
  7,
  18,
  5,
  16,
  18,
  8,
  11,
  18,
  10,
  15,
  9,
  5,
  8,
  14,
  5,
  6,
  54,
  18,
  5,
  7,
  6,
  7,
 

In [16]:
sio.savemat('CG_dataset_rgrs.mat',data_dict)

In [3]:
exp = sio.loadmat(r"C:\Users\liuke\Desktop\NTU2012_mvcnn_gvcnn.mat")

In [13]:
idx = exp['indices'].item()
idx

array([[1],
       [1],
       [1],
       ...,
       [0],
       [0],
       [0]], dtype=uint8)

In [11]:
idx_train = np.where(idx == 1)[0]

In [12]:
idx_train

array([   0,    1,    2, ..., 1636, 1637, 1638], dtype=int64)

In [35]:
def load_ft(data_dir, feature_name):
    data = sio.loadmat(data_dir) # 读取mat文件，是字典形式存储{key:value}
    lbls = data['Y'].astype(np.long)

#     idx = data['indices'].item()
#     print('idx',idx)
    if feature_name == 'CGNN':
        fts = data['X'].astype(np.float32)
    else:
        print(f'wrong feature name{feature_name}!')
        raise IOError

    idx_train=np.zeros(853)  
    idx_test =np.zeros(213) 
    for i in range(853):
        idx_train[i] = i
    for i in range(213):
        idx_test[i] = i+853
    
    return fts, lbls, idx_train, idx_test


In [36]:
fts, lbls, idx_train, idx_test = load_ft(r'CG_dataset_rgrs.mat','CGNN')

In [38]:
idx_test

array([ 853.,  854.,  855.,  856.,  857.,  858.,  859.,  860.,  861.,
        862.,  863.,  864.,  865.,  866.,  867.,  868.,  869.,  870.,
        871.,  872.,  873.,  874.,  875.,  876.,  877.,  878.,  879.,
        880.,  881.,  882.,  883.,  884.,  885.,  886.,  887.,  888.,
        889.,  890.,  891.,  892.,  893.,  894.,  895.,  896.,  897.,
        898.,  899.,  900.,  901.,  902.,  903.,  904.,  905.,  906.,
        907.,  908.,  909.,  910.,  911.,  912.,  913.,  914.,  915.,
        916.,  917.,  918.,  919.,  920.,  921.,  922.,  923.,  924.,
        925.,  926.,  927.,  928.,  929.,  930.,  931.,  932.,  933.,
        934.,  935.,  936.,  937.,  938.,  939.,  940.,  941.,  942.,
        943.,  944.,  945.,  946.,  947.,  948.,  949.,  950.,  951.,
        952.,  953.,  954.,  955.,  956.,  957.,  958.,  959.,  960.,
        961.,  962.,  963.,  964.,  965.,  966.,  967.,  968.,  969.,
        970.,  971.,  972.,  973.,  974.,  975.,  976.,  977.,  978.,
        979.,  980.,

In [57]:
import torch
lbls = torch.Tensor([1,2,3,4,5,6,7])
preds = torch.Tensor([4,3,4,5,6,7,8])


In [58]:
from torch.nn import Linear, Module, MSELoss

In [59]:
criterion = MSELoss(reduction = 'mean')

In [60]:
loss = criterion(lbls,preds)

In [61]:
loss

tensor(2.1429)

In [66]:
# 手搓MSEloss
def RMSE(lbls,preds):
    dsum = 0
    for i in range(len(lbls)):
        yi = lbls[i]
        y_i = preds[i]
        di = ((y_i-yi)/yi)*((y_i-yi)/yi)
        dsum = dsum+di

    rmse = dsum / len(lbls)
    return (rmse)

In [69]:
loss = RMSE(lbls,preds)

In [70]:
loss.item()

1.3588281869888306